
[[keyboard.bindings]]
action = "PasteSelection"
key = "I"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi|~Search"

[general]
live_config_reload = false

[colors.normal]
black = "#090909"
blue = "#407ee7"
cyan = "#00ad9c"
green = "#5ab738"
magenta = "#6666ea"
red = "#f22c40"
white = "#a8a19f"
yellow = "#d5911a"

[colors.primary]
background = "#090909"
foreground = "#EEEEEE"

[colors.vi_mode_cursor]
cursor = "CellForeground"

[cursor]
vi_mode_style = "Block"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "DejaVu Sans Mono"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true

[keyboard]
